# Generated by Django 5.1.7 on 2025-03-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog Post', 'verbose_name_plural': 'Blog Posts'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-subscribed_at'], 'verbose_name': 'Email Subscription', 'verbose_name_plural': 'Email Subscriptions'},
        ),
    ]
